---
version: '3'
services:
  freqtrade:
    image: phuchust/freqtrade-3c-ftx:v1.00.00
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # Build step - only needed when additional dependencies are needed
    build:
      context: .
      dockerfile: "./dockerfile.custom"
    restart: unless-stopped
    container_name: freqtrade-3C-FTX-DCA
    volumes:
      - "./user_data:/freqtrade/user_data"
    # Expose api on port 8080 (localhost only)
    # Please read the https://www.freqtrade.io/en/stable/rest-api/ documentation
    # before enabling this.
    # ports:
    #  - "0.0.0.0:8080"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.log
      --db-url sqlite:////freqtrade/user_data/trades.sqlite
      --config /freqtrade/user_data/config.json
      
